name: Install
description: Install and cache playwright

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: "20.x"
        cache: "yarn"
    - shell: bash
      run: yarn install --frozen-lockfile
    - name: Store playwright version
      shell: bash
      run: |
        PLAYWRIGHT_VERSION=$(YARN_ENABLE_COLORS=false yarn info @playwright/test | grep @playwright | sed 's/.*://')
        echo "Playwright's Version: $PLAYWRIGHT_VERSION"
        echo "PLAYWRIGHT_VERSION=$PLAYWRIGHT_VERSION" >> $GITHUB_ENV
    - name: Cache playwright browsers
      id: cache-playwright-browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: playwright-browsers-${{ env.PLAYWRIGHT_VERSION }}
    - name: Setup playwright browsers
      shell: bash
      if: steps.cache-playwright-browsers.outputs.cache-hit != 'true'
      run: yarn playwright install --with-deps
