name: Test & Build

on:
  workflow_call:
env:
  FORCE_COLOR: true

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: yarn lint
      - run: yarn test:component
      - run: yarn test:e2e
      - name: Move playwright screenshots to output
        run: mv test-results/*.png output/merged/
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-reports
          path: output/merged

  build:
    name: 🛠️ Build
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/install
      - run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          path: dist

  test_build:
    name: 🔬 Test after build
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist
      - uses: ./.github/actions/install
      - run: yarn test:build

  lighthouse:
    name: 💡 Lighthouse
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist
      - uses: treosh/lighthouse-ci-action@v11
        with:
          temporaryPublicStorage: true
